# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    "**.json",
    "**.md",
    "**.txt",
    "**.vm",
    "**/.DS_Store",
    "**/.gitignore",
    "**/*.class",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/CNAME",
    "**/MANIFEST.MF",
    "**/MethodByte.eo",
    "MANIFEST.MF",
    "README.md",
    "renovate.json",
    "src/it/spring-fat/src/main/resources/META-INF/spring.factories",
    "src/main/resources/META-INF/services/javax.xml.transform.TransformerFactory",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2016-2026 Objectionary.com"
SPDX-License-Identifier = "MIT"
